driver:
  name: docker

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: springboot
  pillars-from-files:
    gen_props.sls: test/integration/pillar/gen_props.sls
  pillars:
    top.sls:
      base:
        '*':
          - gen_props
  state_top:
    base:
      '*':
        - springboot
verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos/7

suites:
  - name: gen_props
