language: python
version::
  - '2.7'
env:
  - SALT_VERSION="2015.5.6"
  - SALT_VERSION="2015.8.0"
  - SALT_VERSION="2015.8.1"
before_install:
  - pip install salt==$SALT_VERSION
install:
  # Copy these states
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r . /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion
  - sudo service salt-minion restart

  # Additional debug help
  - sudo cat /var/log/salt/*

  # See what kind of travis box you're on
  - sudo salt-call grains.items --local
before_script:
  # find all the *.sls files
  - states=$(find /srv/salt/$FORMULA -name '*.sls' | while read i; do tmp=$FORMULA.${i##*/}; echo ${tmp%.*}; done | xargs | sed -e 's/ /,/g')
  # See what kind of travis box you're on to help with making your states compatible with travis
  - salt-call grains.items --local
  - ls -l /srv/salt
  - ls -l /tmp
script:
  - sudo salt-call state.show_highstate --local --retcode-passthrough
  # - salt-call --local state.apply springboot --retcode-passthrough -l error test=True $states
